// <auto-generated />
using System;
using FoodDatabase.App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodDatabase.App.Migrations
{
    [DbContext(typeof(FoodDatabaseContext))]
    [Migration("20260709173216_AddRezeptUndRezeptZutat")]
    partial class AddRezeptUndRezeptZutat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("FoodDatabase.App.Models.Lagerort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Lagerorte");
                });

            modelBuilder.Entity("FoodDatabase.App.Models.LebensmittelKatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Einheit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kategorie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NährwertId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("NährwertId");

                    b.ToTable("LebensmittelKatalog");
                });

            modelBuilder.Entity("FoodDatabase.App.Models.Nährwert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Ballaststoffe")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Fett")
                        .HasColumnType("REAL");

                    b.Property<double>("GesättigteFettsäuren")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kalorien")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Kohlenhydrate")
                        .HasColumnType("REAL");

                    b.Property<int>("LebensmittelId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Protein")
                        .HasColumnType("REAL");

                    b.Property<double>("Salz")
                        .HasColumnType("REAL");

                    b.Property<string>("StandardMengeEinheit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Zucker")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("LebensmittelId")
                        .IsUnique();

                    b.ToTable("Nährwerte");
                });

            modelBuilder.Entity("FoodDatabase.App.Models.ProduktInstanz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Einkaufsdatum")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lagerort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LebensmittelKatalogId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Menge")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MindestbestandMenge")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Verfallsdatum")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LebensmittelKatalogId");

                    b.ToTable("ProduktInstanzen");
                });

            modelBuilder.Entity("FoodDatabase.App.Models.Rezept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Portionen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Schwierigkeitsgrad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Zubereitung")
                        .HasColumnType("TEXT");

                    b.Property<int>("ZubereitungszeitMinuten")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Rezepte");
                });

            modelBuilder.Entity("FoodDatabase.App.Models.RezeptZutat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Einheit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LebensmittelId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Menge")
                        .HasColumnType("REAL");

                    b.Property<string>("Notizen")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RezeptId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LebensmittelId");

                    b.HasIndex("RezeptId", "Position")
                        .IsUnique();

                    b.ToTable("RezeptZutaten");
                });

            modelBuilder.Entity("FoodDatabase.App.Models.LebensmittelKatalog", b =>
                {
                    b.HasOne("FoodDatabase.App.Models.Nährwert", "Nährwert")
                        .WithMany()
                        .HasForeignKey("NährwertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nährwert");
                });

            modelBuilder.Entity("FoodDatabase.App.Models.Nährwert", b =>
                {
                    b.HasOne("FoodDatabase.App.Models.LebensmittelKatalog", "LebensmittelKatalog")
                        .WithMany()
                        .HasForeignKey("LebensmittelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LebensmittelKatalog");
                });

            modelBuilder.Entity("FoodDatabase.App.Models.ProduktInstanz", b =>
                {
                    b.HasOne("FoodDatabase.App.Models.LebensmittelKatalog", "LebensmittelKatalog")
                        .WithMany()
                        .HasForeignKey("LebensmittelKatalogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LebensmittelKatalog");
                });

            modelBuilder.Entity("FoodDatabase.App.Models.RezeptZutat", b =>
                {
                    b.HasOne("FoodDatabase.App.Models.LebensmittelKatalog", "Lebensmittel")
                        .WithMany()
                        .HasForeignKey("LebensmittelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoodDatabase.App.Models.Rezept", "Rezept")
                        .WithMany("Zutaten")
                        .HasForeignKey("RezeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lebensmittel");

                    b.Navigation("Rezept");
                });

            modelBuilder.Entity("FoodDatabase.App.Models.Rezept", b =>
                {
                    b.Navigation("Zutaten");
                });
#pragma warning restore 612, 618
        }
    }
}
