// <auto-generated />
using System;
using FoodDatabase.App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodDatabase.App.Migrations
{
    [DbContext(typeof(FoodDatabaseContext))]
    partial class FoodDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("FoodDatabase.App.Models.Lagerort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Lagerorte");
                });

            modelBuilder.Entity("FoodDatabase.App.Models.LebensmittelKatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Einheit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kategorie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LebensmittelKatalog");
                });

            modelBuilder.Entity("FoodDatabase.App.Models.ProduktInstanz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Einkaufsdatum")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lagerort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LebensmittelKatalogId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Menge")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MindestbestandMenge")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Verfallsdatum")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LebensmittelKatalogId");

                    b.ToTable("ProduktInstanzen");
                });

            modelBuilder.Entity("FoodDatabase.App.Models.ProduktInstanz", b =>
                {
                    b.HasOne("FoodDatabase.App.Models.LebensmittelKatalog", "LebensmittelKatalog")
                        .WithMany()
                        .HasForeignKey("LebensmittelKatalogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LebensmittelKatalog");
                });
#pragma warning restore 612, 618
        }
    }
}
